services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gighood_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
